// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define SARABUN_12_FONT_ID (975592514)
#define SARABUN_14_FONT_ID (-904724760)
#define SARABUN_16_FONT_ID (-1852798369)
#define SARABUN_18_FONT_ID (1135066893)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (-469187504)
#define UI_12_FONT_ID (1381346164)
#define SMALL_FONT_ID (317376875)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(SARABUN_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SARABUN_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SARABUN_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SARABUN_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
